package riscv

import spinal.core._

/** Run with the included sbt build (SpinalHDL 1.12.3 / Scala 2.13.14).
  * Generated RTL defaults to the ignored generated/ output directory.
  * Arguments: cpu|soc|cmod|peripherals, output directory, external image path.
  * Defaults to Cmod with bootloader.mem from the project working directory.
  * Every target containing IMEM requires a readable, nonempty boot image.
  * For FPGA builds pass the real bootloader image and include clk_wiz_0 IP.
  */
object Generate extends App {
  val target = args.headOption.getOrElse("cmod")
  require(Set("cpu", "soc", "cmod", "peripherals").contains(target), s"Unknown target: $target")
  val output = args.lift(1).getOrElse(s"generated/$target")
  val imagePath = args.lift(2).getOrElse("bootloader.mem")
  require(imagePath != "--no-image",
    "--no-image is no longer supported. Supply bootloader.mem for targets containing IMEM.")
  if (target != "cpu") {
    val file = new java.io.File(imagePath)
    require(file.isFile && file.canRead && file.length() > 0,
      s"Bootloader image is required: ${file.getAbsolutePath}. " +
        "Place bootloader.mem in the project directory or pass its path as the third argument. " +
        "No RTL has been generated by this invocation.")
  }
  val config = SpinalConfig(targetDirectory = output)
  val image = Some(imagePath)
  target match {
    case "cpu" => config.generateVerilog(new riscv_cpu)
    case "soc" => config.generateVerilog(new riscv_soc(image))
    case "cmod" => config.generateVerilog(new cmod_a7_top(image))
    case "peripherals" =>
      config.generateVerilog(new uart)
      config.generateVerilog(new timer)
      config.generateVerilog(new gpio)
      config.generateVerilog(new system_control)
      config.generateVerilog(new performance_counter)
      config.generateVerilog(new address_resolver_mem)
      config.generateVerilog(new imem_if(image))
      config.generateVerilog(new dmem_mem)
    case other => sys.error(s"Unknown target: $other")
  }
}
